// Helper functions to get localized options (using original correct values)
export const getSeniorityOptions = (t: any) => [
  { value: "any", label: t('seniority.all') },
  { value: "estagio", label: t('seniority.internship') },
  { value: "assistente", label: t('seniority.assistant') },
  { value: "junior", label: t('seniority.junior') },
  { value: "pleno", label: t('seniority.mid') },
  { value: "senior", label: t('seniority.senior') },
  { value: "diretor", label: t('seniority.director') },
  { value: "executivo", label: t('seniority.executive') },
]

export const getLinkedinTimePostedOptions = (t: any) => [
  { value: "any", label: t('timePosted.any') },
  { value: "r900", label: t('timePosted.quarterHour') },
  { value: "r1800", label: t('timePosted.halfHour') },
  { value: "r3600", label: t('timePosted.hour') },
  { value: "r18000", label: t('timePosted.last5Hours') },
  { value: "r86400", label: t('timePosted.day') },
  { value: "r604800", label: t('timePosted.week') },
  { value: "r2592000", label: t('timePosted.month') },
]

export const getIndeedTimePostedOptions = (t: any) => [
  { value: "any", label: t('timePosted.any') },
  { value: "last", label: t('timePosted.last5Hours') },
  { value: "1", label: t('timePosted.day') },
  { value: "3", label: t('timePosted.3days') },
  { value: "7", label: t('timePosted.week') },
  { value: "14", label: t('timePosted.2weeks') },
]

export const getWorkModelOptions = (t: any) => [
  { value: "any", label: t('workModel.all') },
  { value: "presencial", label: t('workModel.onsite') },
  { value: "remoto", label: t('workModel.remote') },
  { value: "hibrido", label: t('workModel.hybrid') },
]

export const getSearchModeOptions = (t: any) => [
  { value: "preciso", label: t('searchMode.precise') },
  { value: "poderoso", label: t('searchMode.powerful') },
]

export const linkedinSeniorityMap = {
  estagio: "1", // Internship
  assistente: "2", // Entry level
  junior: "3", // Associate
  pleno: "4", // Mid-Senior level
  senior: "4", // Mid-Senior level (LinkedIn agrupa Pleno e Sênior sob o mesmo código)
  diretor: "5", // Director
  executivo: "6", // Executive
}

export const linkedinWorkModelMap = {
  presencial: "1",
  remoto: "2",
  hibrido: "3",
}

// Exclusões por locale
export const exclusionsByLocale = {
  "pt-BR": {
    linkedin: {
      estagio: [
        "Assistente",
        "Júnior",
        "Junior",
        "Pleno",
        "Sênior",
        "Senior",
        "Especialista",
        "Executivo",
        "Coordenador",
        "Gerente",
        "Diretor",
        "JR",
        "PL",
        "SR",
      ],
      assistente: [
        "Estágio",
        "Estagio",
        "Trainee",
        "Júnior",
        "Junior",
        "Pleno",
        "Sênior",
        "Senior",
        "Especialista",
        "Executivo",
        "Coordenador",
        "Gerente",
        "Diretor",
        "JR",
        "PL",
        "SR",
      ],
      junior: [
        "Estágio",
        "Estagio",
        "Trainee",
        "Assistente",
        "Pleno",
        "Sênior",
        "Senior",
        "Especialista",
        "Executivo",
        "Coordenador",
        "Gerente",
        "Diretor",
        "PL",
        "SR",
      ],
      pleno: [
        "Estágio",
        "Estagio",
        "Trainee",
        "Assistente",
        "Júnior",
        "Junior",
        "Sênior",
        "Senior",
        "Especialista",
        "Executivo",
        "Coordenador",
        "Gerente",
        "Diretor",
        "JR",
        "SR",
      ],
      senior: [
        "Estágio",
        "Estagio",
        "Trainee",
        "Assistente",
        "Júnior",
        "Junior",
        "Pleno",
        "Coordenador",
        "Gerente",
        "Diretor",
        "JR",
        "PL",
      ],
      diretor: [
        "Estágio",
        "Estagio",
        "Trainee",
        "Assistente",
        "Júnior",
        "Junior",
        "Pleno",
        "Sênior",
        "Senior",
        "Especialista",
      ],
      executivo: [
        "Estágio",
        "Estagio",
        "Trainee",
        "Assistente",
        "Júnior",
        "Junior",
        "Pleno",
        "Sênior",
        "Senior",
        "Especialista",
        "Coordenador",
        "Gerente",
      ],
    },
    indeed: {
      estagio: [
        "Júnior",
        "Junior",
        "Pleno",
        "Sênior",
        "Senior",
        "Especialista",
        "Executivo",
        "Coordenador",
        "Gerente",
        "Diretor",
        "JR",
        "PL",
        "SR",
      ],
      junior: [
        "Estágio",
        "Estagio",
        "Trainee",
        "Pleno",
        "Sênior",
        "Senior",
        "Especialista",
        "Executivo",
        "Coordenador",
        "Gerente",
        "Diretor",
        "PL",
        "SR",
      ],
      pleno: [
        "Estágio",
        "Estagio",
        "Trainee",
        "Júnior",
        "Junior",
        "Sênior",
        "Senior",
        "Especialista",
        "Executivo",
        "Coordenador",
        "Gerente",
        "Diretor",
        "JR",
        "SR",
      ],
      senior: [
        "Estágio",
        "Estagio",
        "Trainee",
        "Júnior",
        "Junior",
        "Pleno",
        "Coordenador",
        "Gerente",
        "Diretor",
        "JR",
        "PL",
      ],
      especialista: [
        "Estágio",
        "Estagio",
        "Trainee",
        "Júnior",
        "Junior",
        "Pleno",
      ],
    }
  },
  "en": {
    linkedin: {
      estagio: [
        "Assistant",
        "Junior",
        "Mid-level",
        "Senior",
        "Specialist",
        "Executive",
        "Coordinator",
        "Manager",
        "Director",
        "JR",
        "MID",
        "SR",
      ],
      assistente: [
        "Intern",
        "Internship",
        "Trainee",
        "Junior",
        "Mid-level",
        "Senior",
        "Specialist",
        "Executive",
        "Coordinator",
        "Manager",
        "Director",
        "JR",
        "MID",
        "SR",
      ],
      junior: [
        "Intern",
        "Internship",
        "Trainee",
        "Assistant",
        "Mid-level",
        "Senior",
        "Specialist",
        "Executive",
        "Coordinator",
        "Manager",
        "Director",
        "MID",
        "SR",
      ],
      pleno: [
        "Intern",
        "Internship",
        "Trainee",
        "Assistant",
        "Junior",
        "Senior",
        "Specialist",
        "Executive",
        "Coordinator",
        "Manager",
        "Director",
        "JR",
        "SR",
      ],
      senior: [
        "Intern",
        "Internship",
        "Trainee",
        "Assistant",
        "Junior",
        "Mid-level",
        "Coordinator",
        "Manager",
        "Director",
        "JR",
        "MID",
      ],
      diretor: [
        "Intern",
        "Internship",
        "Trainee",
        "Assistant",
        "Junior",
        "Mid-level",
        "Senior",
        "Specialist",
      ],
      executivo: [
        "Intern",
        "Internship",
        "Trainee",
        "Assistant",
        "Junior",
        "Mid-level",
        "Senior",
        "Specialist",
        "Coordinator",
        "Manager",
      ],
    },
    indeed: {
      estagio: [
        "Junior",
        "Mid-level",
        "Senior",
        "Specialist",
        "Executive",
        "Coordinator",
        "Manager",
        "Director",
        "JR",
        "MID",
        "SR",
      ],
      junior: [
        "Intern",
        "Internship",
        "Trainee",
        "Mid-level",
        "Senior",
        "Specialist",
        "Executive",
        "Coordinator",
        "Manager",
        "Director",
        "MID",
        "SR",
      ],
      pleno: [
        "Intern",
        "Internship",
        "Trainee",
        "Junior",
        "Senior",
        "Specialist",
        "Executive",
        "Coordinator",
        "Manager",
        "Director",
        "JR",
        "SR",
      ],
      senior: [
        "Intern",
        "Internship",
        "Trainee",
        "Junior",
        "Mid-level",
        "Coordinator",
        "Manager",
        "Director",
        "JR",
        "MID",
      ],
      especialista: [
        "Intern",
        "Internship",
        "Trainee",
        "Junior",
        "Mid-level",
      ],
    }
  }
}

// Backward compatibility - mantém as exportações originais para português
export const linkedinExclusions = exclusionsByLocale["pt-BR"].linkedin

export const indeedExclusions = exclusionsByLocale["pt-BR"].indeed 